name: "Automatic Releases"

on:
  milestone:
    types:
      - "closed"

permissions:
  packages: "write"
  
jobs:
  release:
    uses: laminas/workflow-automatic-releases/.github/workflows/release-on-milestone-closed.yml@1.x
    secrets:
      GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
      GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORGANIZATION_ADMIN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
